brew installation, error checking

diff --git a/dependencies b/dependencies
--- a/dependencies
+++ b/dependencies
@@ -1,9 +1,21 @@
 #!/usr/bin/env bash
 
+FAIL_FAST=1
 if [[ 'Darwin' == $(uname -s) ]]; then
   if [[ ! -x /usr/local/bin/brew ]]; then
-    echo "No fun without brew! Let's try to install it unsupervised."
+    echo "proenv::dependencies:: No fun without brew! Let's try to install it unsupervised."
+    # unlock access as root to avoid passwords after this
+    echo -e "$USER \tALL="'(ALL) '"\tNOPASSWD: ALL" | sudo tee -a /etc/sudoers
     "${REPO}/.git/brew.install"
+    if [[ 0 != $? ]]; then
+      echo "proenv::dependencies:: brew.install failed"
+      if [[ 1 == $FAIL_FAST ]]; then
+        echo "proenv::dependencies:: FAIL_FAST is enabled, exiting"
+        exit 1
+      else
+        echo "proenv::dependencies:: FAIL_FAST is disabled"
+      fi
+    fi
   fi
 
   if [[ 5 != $BASH_VERSINFO ]]; then
diff --git a/hooks/post-checkout b/hooks/post-checkout
--- a/hooks/post-checkout
+++ b/hooks/post-checkout
@@ -50,10 +50,21 @@ installClonedReposHooks() {
     cd - >/dev/null
 }
 
+FAIL_FAST=1
 invokeClonedReposPostCloneHook() {
   if [[ -d ${REPO}/.git/hooks/post-clone.d ]]; then
     for pc in $(find ${REPO}/.git/hooks/post-clone.d -mindepth 1); do
+      echo "proenv::post-clone:: \${pc}='${pc}'"
       [[ -x ${pc} ]] && REPO="${REPO}" ${pc}
+      if [[ 0 != $? ]]; then
+        echo "proenv::post-clone:: \${pc}=${pc} failed"
+        if [[ 1 == $FAIL_FAST ]]; then
+          echo "FAIL_FAST is enabled, exiting"
+          return 1
+        else
+          echo "FAIL_FAST is disabled"
+        fi
+      fi
     done
   else
     local -r post_clone_hook="${REPO}/.git/hooks/post-clone"
diff --git a/install b/install
--- a/install
+++ b/install
@@ -55,7 +55,17 @@ if [[ 1 == $GITIGNORE_CHANGED ]]; then
 fi
 
 # execute dependencies and direnv register repository's .envrc
+FAIL_FAST=1
 REPO="${REPO}" $(dirname $0)/dependencies
+if [[ 0 != $? ]]; then
+  echo "proenv::install dependencies ${pc} failed"
+  if [[ 1 == $FAIL_FAST ]]; then
+    echo "FAIL_FAST is enabled, exiting"
+    exit 1
+  else
+    echo "FAIL_FAST is disabled"
+  fi
+fi
 direnv allow "${REPO}"
 
 # cleanup .git directory from template assets
diff --git a/modules/vagrant/install b/modules/vagrant/install
--- a/modules/vagrant/install
+++ b/modules/vagrant/install
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
+[[ ! -x /usr/local/bin/brew ]] && echo 'no brew, exit' && exit 1
 [[ -z $REPO ]] && echo 'REPO undefined' >&2 && exit 1
 [[ ! -f ${REPO}/Vagrantfile ]] && exit 0
 
 if [[ 'Darwin' == $(uname -s) ]]; then
   VAGRANT_EXEC="$(which vagrant)"
   if [[ -z $VAGRANT_EXEC ]]; then
-    echo "proenv:: vagrant not found installing with brew" >&2
+    echo "proenv::vagrant::install vagrant not found installing with brew" >&2
     brew install vagrant
     VAGRANT_EXEC='/usr/local/bin/vagrant'
   elif [[ '/usr/local/bin/vagrant' != $VAGRANT_EXEC ]]; then
diff --git a/share/hooks/common b/share/hooks/common
--- a/share/hooks/common
+++ b/share/hooks/common
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+FAIL_FAST=1
+
 readonly REPO="$(git rev-parse --show-toplevel)"
 exec_dotd() {
   readonly pc_dir="${REPO}/.git/hooks/${1}.d"
@@ -7,6 +9,15 @@ exec_dotd() {
   if [[ -d ${pc_dir} ]]; then
     for pc in $(find "${pc_dir}" -mindepth 1); do
       [[ -x ${pc} ]] && REPO="${REPO}" ${pc} $@
+      if [[ 0 != $? ]]; then
+        echo "proenv::common:: post-clone ${pc} failed"
+        if [[ 1 == $FAIL_FAST ]]; then
+          echo "FAIL_FAST is enabled, exiting"
+          return 1
+        else
+          echo "FAIL_FAST is disabled"
+        fi
+      fi
     done
   fi
 }
